<?php
/**
 * This page handles ajax request for calendar appointments. Ajax request is generated by bootstrap-calendar.js.
 *
  */

    require_once('Controller.class.php');

    $ctrl = new Controller();

    // call the method in Controller class to retrieve appointment details from DB.
    if (isset($_GET['calendar_id']))
    {
        $empid = $_GET['calendar_id'];
        $ts = $_GET['timestamp'];

        // Check if we are actually making a booking or just confirming a selection
        if ( empty($_POST) )
        {
            $ctrl->bookingConfirm($empid, $ts);

        } else if ($_POST['a'] == 'create')
        {
            $ctrl->bookingCreate($empid, $ts);
        }
    }
