<?php
/**
 * This page handles ajax request for calendar appointments. Ajax request is generated by bootstrap-calendar.js.
 *
  */

    require_once('Controller.class.php');

    $ctrl = new Controller();

    $empNo = $_POST['id'];

// call the method in Controller class to retrieve appointment details from DB.
    $ctrl->getCustCal($empNo);
    