<?php
/**
 * This page handles ajax request for calendar appointments. Ajax request is generated by bootstrap-calendar.js.
 *
  */

    require_once('Controller.class.php');

    $ctrl = new Controller();

    // call the method in Controller class to retrieve appointment details from DB.
    if(isset($_POST['calendar_type'])
    && !empty($_POST['calendar_type'])
    && isset($_POST['id'])
    && is_numeric($_POST['id'])
    && isset($_POST['number_of_weeks'])
    && is_numeric($_POST['number_of_weeks']))
    {
    
        $empno = $_POST['id'];
        $caltype = $_POST['calendar_type'];
        $weeks = $_POST['number_of_weeks'];
        
        $ctrl->getCustCal($empno, $weeks, $caltype);
    }