<?php
/**
 * This page handles ajax request for calendar appointments. Ajax request is generated by bootstrap-calendar.js.
 *
  */

    require_once('Controller.class.php');

    $ctrl = new Controller();

    // call the method in Controller class to retrieve appointment details from DB.
    //$empno = $_POST['id'];
    //$caltype = $_POST['calendar_type'];
    //$weeks = $_POST['number_of_weeks'];
    
    $ctrl->makeBooking();
